@startuml

skinparam class {
	BackgroundColor greenyellow
	ClassHeaderBackgroundColor yellow
	ArrowColor #0ACF97
	BorderColor #d5d5d5
}

class Document { 
	+Save()
	+Open()
	+Close()
	{abstract} +DoRead()
}

class MyDocument {
	+DoRead()
}

class Apllication {
	+AddDocument()
	+OpenDocument()
	{abstract} +DoCreateDocument()
	{abstract} +CanOpenDocument()
	{abstract} +AbountToOpenDocument()
}

class MyApplication {
	+DoCreateDocument()
	+CanOpenDocument()
	+AbountToOpenDocument()
}

Document <|-- MyDocument
Apllication <|-- MyApplication
MyDocument <.. MyApplication
Document <--o "docs" Apllication

@enduml
